# Generated by Django 4.0.3 on 2023-05-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stand',
            field=models.TextField(null=True),
        ),
    ]
