# Generated by Django 4.0.3 on 2023-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_alter_person_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='pot',
            field=models.IntegerField(null=True),
        ),
    ]
