# Generated by Django 4.0.3 on 2023-06-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_pots_person_pot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=4),
        ),
    ]
