# Generated by Django 4.0.3 on 2023-06-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_alter_position_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stand',
        ),
    ]
