# Generated by Django 4.0.3 on 2023-06-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_alter_pots_pot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pots',
            old_name='pot_id',
            new_name='pot_name',
        ),
    ]
