# Generated by Django 4.0.3 on 2023-06-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_rename_pot_id_pots_pot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='pot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pots',
            name='pot_name',
            field=models.CharField(max_length=3),
        ),
    ]
