# Generated by Django 4.0.3 on 2023-06-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0012_alter_person_position_alter_person_pot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sp_check',
            field=models.IntegerField(null=True),
        ),
    ]
