# Generated by Django 4.0.3 on 2023-06-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_remove_person_sp_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='odr',
            field=models.IntegerField(null=True),
        ),
    ]
